annotations:
  artifacthub.io/changes: |
    - Add upgrader framework job
    - Add additional Alert Engine configuration
    - Add additional logback loggers configuration
    - Clean Redis configuration in the `values.yaml` file
    - Add documentation for alert engine connector ssl
    - Add AE engine list support
    - Allow users to define their own configuration file by defining a volume
apiVersion: v1
appVersion: 3.18.10
description: Official Gravitee.io Helm chart for API Management 3.x
home: https://gravitee.io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
- gravitee.io
- gravitee
- graviteeio
- API
- API Management
kubeVersion: '>=1.14.0-0'
name: apim3
sources:
- https://github.com/gravitee-io
version: 3.1.60
